name: Build, push, and deploy

on:
  push:
  workflow_dispatch:
    inputs:
      destination:
        type: string
        description: Destination path in the CDN for the deployment
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CDN_PATH: ${{ inputs.destination || 'latest' }}

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install lint dependencies
        run: bun install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run lint
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build application
        run: bun run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: app-dist
          path: dist

  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    environment: dev-cdn
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist
      - name: Upload to CDN dev path
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: personoversikt
          source: dist
          destination: /internarbeidsflate-decorator-v3/dev/${{ env.CDN_PATH }}
          cache_invalidation: true
          headers: |-
            cache-control: public, max-age=300

  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    environment: prod-cdn
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist
      - name: Upload to CDN prod path
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: personoversikt
          source: dist
          destination: /internarbeidsflate-decorator-v3/prod/${{ env.CDN_PATH }}
          cache_invalidation: true
          headers: |-
            cache-control: public, max-age=600
